package consts

const TemplateGenDaoEntityContent = `
// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. {TplDatetimeStr}
// =================================================================================

package entity

{TplPackageImports}

// {TplTableNameCamelCase} is the golang structure for table {TplTableName}.
{TplStructDefine}
`
