package main

const httpGenVersion = "v0.0.1"

const templateSvcStruct = `
// Unimplemented{{.svc_name}}Server
type Unimplemented{{.svc_name}}Server struct {
	impl {{.svc_name}}Impl
}

// Register{{.svc_name}}Server is an entry that must be implemented.
func Register{{.svc_name}}Server(impl {{.svc_name}}Impl) Unimplemented{{.svc_name}}Server {
	return Unimplemented{{.svc_name}}Server{impl: impl}
}`

const templateRouterFunc = `
// {{.method_name}} {{.method_comment}}
func ({{.svc_name}} Unimplemented{{.svc_name}}Server) {{.method_name}}(ctx context.Context, req *{{.in_name}}) (*{{.out_name}}, error) {
	// 这个ctx key需要放到gf的常量中去
	ctx = context.WithValue(ctx, "ctx_http_pattern", "{{.http_pattern}}")
	ctx = context.WithValue(ctx, "ctx_http_method","{{.http_method}}")
	ctx = context.WithValue(ctx, "ctx_grpc_pattern", "/{{.svr_name}}/{{.original_name}}")
	return {{.svc_name}}.impl.{{.method_name}}(ctx, req)
}
`

const templateImplStruct = `
// {{.svc_name}}Impl is the server API for {{.svc_name}} service.
type {{.svc_name}}Impl interface {
	{{- range .svc_list}}
	{{.method_name}} (ctx context.Context, req *{{.in_name}}) (*{{.out_name}}, error)
	{{- end}}
}
`

const versionComment = `
// Code generated by protoc-gen-go-ghttp. DO NOT EDIT.
// versions:
// 	protoc-gen-go-http {{.ghttp_version}}
// 	protoc             {{.protoc_version}}
// source: {{.source_path}}`

const methodMessageStruct = `
// {{.message_name}} {{.method_comment}}
type {{.message_name}} struct {
	{{- range .fields}}
		{{.}}
	{{- end}}
}
`
