// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package article

import (
	"github.com/gogf/gf/cmd/gf/v2/internal/cmd/testdata/genctrl/multi/api/admin/article"
)

type ControllerV1 struct{}

func NewV1() article.IArticleV1 {
	return &ControllerV1{}
}
