// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package article

import (
	"github.com/gogf/gf/cmd/gf/v2/internal/cmd/testdata/genctrl/api/article"
)

type ControllerV1 struct{}

func NewV1() article.IArticleV1 {
	return &ControllerV1{}
}

type ControllerV2 struct{}

func NewV2() article.IArticleV2 {
	return &ControllerV2{}
}
