// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"/internal"
)

// internalUser4Dao is internal type for wrapping internal DAO implements.
type internalUser4Dao = *internal.User4Dao

// user4Dao is the data access object for table user4.
// You can define custom methods on it to extend its functionality as you wish.
type user4Dao struct {
	internalUser4Dao
}

var (
	// User4 is globally public accessible object for table user4 operations.
	User4 = user4Dao{
		internal.NewUser4Dao(),
	}
)

// Fill with you ideas below.
