// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"/internal"
)

// internalUser3Dao is an internal type for wrapping the internal DAO implementation.
type internalUser3Dao = *internal.User3Dao

// user3Dao is the data access object for the table user3.
// You can define custom methods on it to extend its functionality as needed.
type user3Dao struct {
	internalUser3Dao
}

var (
	// User3 is a globally accessible object for table user3 operations.
	User3 = user3Dao{
		internal.NewUser3Dao(),
	}
)

// Add your custom methods and functionality below.
