// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"/internal"
)

// internalUser3Dao is internal type for wrapping internal DAO implements.
type internalUser3Dao = *internal.User3Dao

// user3Dao is the data access object for table user3.
// You can define custom methods on it to extend its functionality as you wish.
type user3Dao struct {
	internalUser3Dao
}

var (
	// User3 is globally public accessible object for table user3 operations.
	User3 = user3Dao{
		internal.NewUser3Dao(),
	}
)

// Fill with you ideas below.
