// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dict

import (
	"github.com/gogf/gf/cmd/gf/v2/internal/cmd/testdata/genctrl-merge/add_new_file/api/dict"
)

type ControllerV1 struct{}

func NewV1() dict.IDictV1 {
	return &ControllerV1{}
}
