// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

// I am not overwritten.

package dao

import (
	"/internal"
)

// internalUser2Dao is internal type for wrapping internal DAO implements.
type internalUser2Dao = *internal.User2Dao

// user2Dao is the data access object for table user2.
// You can define custom methods on it to extend its functionality as you wish.
type user2Dao struct {
	internalUser2Dao
}

var (
	// User2 is globally public accessible object for table user2 operations.
	User2 = user2Dao{
		internal.NewUser2Dao(),
	}
)

// Fill with you ideas below.
