// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

// I am not overwritten.

package dao

import (
	"/internal"
)

// internalUser1Dao is internal type for wrapping internal DAO implements.
type internalUser1Dao = *internal.User1Dao

// user1Dao is the data access object for table user1.
// You can define custom methods on it to extend its functionality as you wish.
type user1Dao struct {
	internalUser1Dao
}

var (
	// User1 is globally public accessible object for table user1 operations.
	User1 = user1Dao{
		internal.NewUser1Dao(),
	}
)

// Fill with you ideas below.
