// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

// I am not overwritten.

package dao

import (
	"/internal"
)

// internalUser1Dao is an internal type for wrapping the internal DAO implementation.
type internalUser1Dao = *internal.User1Dao

// user1Dao is the data access object for the table user1.
// You can define custom methods on it to extend its functionality as needed.
type user1Dao struct {
	internalUser1Dao
}

var (
	// User1 is a globally accessible object for table user1 operations.
	User1 = user1Dao{
		internal.NewUser1Dao(),
	}
)

// Add your custom methods and functionality below.
