// Copyright GoFrame Author(https://goframe.org). All Rights Reserved.
//
// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT was not distributed with this file,
// You can obtain one at https://github.com/gogf/gf.

package mysql_test

import (
	"testing"

	"github.com/gogf/gf/v3/encoding/gjson"
	"github.com/gogf/gf/v3/frame/g"
	"github.com/gogf/gf/v3/os/gtime"
	"github.com/gogf/gf/v3/test/gtest"
	"github.com/gogf/gf/v3/util/gmeta"
)

func Test_Model_Builder(t *testing.T) {
	table := createInitTable()
	defer dropTable(table)

	gtest.C(t, func(t *gtest.T) {
		m := db.Model(table)
		b := m.Builder()

		all, err := m.Where(
			b.Where("id", g.Slice{1, 2, 3}).WhereOr("id", g.Slice{4, 5, 6}),
		).All(ctx)
		t.AssertNil(err)
		t.Assert(len(all), 6)
	})

	// Where And
	gtest.C(t, func(t *gtest.T) {
		m := db.Model(table)

		all, err := m.Where(
			m.Builder().Where("id", g.Slice{1, 2, 3}).WhereOr("id", g.Slice{4, 5, 6}),
		).Where(
			m.Builder().Where("id", g.Slice{2, 3}).WhereOr("id", g.Slice{5, 6}),
		).Where(
			m.Builder().Where("id", g.Slice{3}).Where("id", g.Slice{1, 2, 3}),
		).All(ctx)
		t.AssertNil(err)
		t.Assert(len(all), 1)
	})
	return

	// Where Or
	gtest.C(t, func(t *gtest.T) {
		m := db.Model(table)

		all, err := m.WhereOr(
			m.Builder().Where("id", g.Slice{1, 2, 3}).WhereOr("id", g.Slice{4, 5, 6}),
		).WhereOr(
			m.Builder().Where("id", g.Slice{2, 3}).WhereOr("id", g.Slice{5, 6}),
		).WhereOr(
			m.Builder().Where("id", g.Slice{3}).Where("id", g.Slice{1, 2, 3}),
		).All(ctx)
		t.AssertNil(err)
		t.Assert(len(all), 6)
	})

	// Where with struct which has a field type of *gtime.Time
	gtest.C(t, func(t *gtest.T) {
		m := db.Model(table)

		type Query struct {
			Id       interface{}
			Nickname *gtime.Time
		}

		where, args := m.Builder().Where(&Query{Id: 1}).Build(ctx)
		t.Assert(where, "`id`=? AND `nickname` IS NULL")
		t.Assert(args, []interface{}{1})
	})

	// Where with struct which has a field type of *gjson.Json
	gtest.C(t, func(t *gtest.T) {
		m := db.Model(table)

		type Query struct {
			Id       interface{}
			Nickname *gjson.Json
		}

		where, args := m.Builder().Where(&Query{Id: 1}).Build(ctx)
		t.Assert(where, "`id`=? AND `nickname` IS NULL")
		t.Assert(args, []interface{}{1})
	})

	// Where with do struct which has a field type of *gtime.Time and generated by gf cli
	gtest.C(t, func(t *gtest.T) {
		m := db.Model(table)

		type Query struct {
			gmeta.Meta `orm:"do:true"`
			Id         interface{}
			Nickname   *gtime.Time
		}

		where, args := m.Builder().Where(&Query{Id: 1}).Build(ctx)
		t.Assert(where, "`id`=?")
		t.Assert(args, []interface{}{1})
	})

	// Where with do struct which has a field type of *gjson.Json and generated by gf cli
	gtest.C(t, func(t *gtest.T) {
		m := db.Model(table)

		type Query struct {
			gmeta.Meta `orm:"do:true"`
			Id         interface{}
			Nickname   *gjson.Json
		}

		where, args := m.Builder().Where(&Query{Id: 1}).Build(ctx)
		t.Assert(where, "`id`=?")
		t.Assert(args, []interface{}{1})
	})
}
