// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package hello

import (
	"github.com/gogf/gf/cmd/gf/v2/internal/cmd/testdata/issue/3460/api/hello"
)

type ControllerV1 struct{}

func NewV1() hello.IHelloV1 {
	return &ControllerV1{}
}

type ControllerV2 struct{}

func NewV2() hello.IHelloV2 {
	return &ControllerV2{}
}
