# Rule description: If an issue author updates or comments on an issue while it is not active and has not been closed, the inactive tag will be removed
name: Issue Remove Inactive

on:
  issues:
    types: [edited]
  issue_comment:
    types: [created, edited]

env: # Set environment variables
  TZ: Asia/Shanghai #Time zone (setting the time zone allows the 'Last Updated' on the page to use the time zone)

permissions:
  contents: read

jobs:
  issue-remove-inactive:
    permissions:
      issues: write # to remove the inactive label
    runs-on: ubuntu-latest
    steps:
      - name: remove inactive
        if: github.event.issue.state == 'open'
        uses: actions/github-script@v9
        with:
          script: |
            const LABEL = 'inactive'
            const labels = context.payload.issue.labels.map(l => l.name)
            if (!labels.includes(LABEL)) return

            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              name: LABEL,
            })
